import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "WEB TUTORIALS",
  description: "Generated by LFTY",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1><Link href="/">WEB - src/app/layout.js</Link></h1>

        {children}

        <h3>courses - src/app/layout.js</h3>
        <ol>
          <li><Link href="/read/1">HTML</Link></li>
          <li><Link href="/read/2">CSS</Link></li>
        </ol>
        <h3>actions: - src/app/layout.js</h3>
        <ul>
          <li><Link href="/create">create</Link></li>
          <li><Link href="/update/1">update</Link></li>
          <li><input type="button" value="delete" /></li>
        </ul>
      </body>
    </html>
  );
}
